name: Build and Push Docker Image to GHCR

# Trigger: Run this on every push to the 'main' branch
on:
  push:
    branches:
      - 'main'

# Environment: Define variables
env:
  # The name of the Docker image
  IMAGE_NAME: ${{ github.repository }}

# Jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest 

    # Permissions: Give this job permission to write to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Check out your code from the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN is a secret automatically provided by GitHub
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract metadata (like tags and labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            # tag with'latest'
            type=raw,value=latest,enable=true
            # tag the new commit SHA
            type=sha,format=short,suffix=-astro,enable=true

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}